### ISSUE TITLE
feat: Request to write output log as an "Extra Book"

### ISSUE THREAD

**Issue by darcywong00** [mseag/sfm-utils#5]
As we iterate over the latest set of txt files, we've been copying the console log to an output file. It contains FYI about when a chapter has an unexpected number of verses.

(edited)
@sdysart requests 
> I want to include the output file as an 'extra book' so the content isn't lost. I've edited the output txt file so that it will work with Paratext, and then I imported it into Paratext.
>
> Basically I
> * added `\id XXA - [Project Name]` as the first line. This tells Paratext to make an extra book 'A'. Paratext will ignore all text above the `\id` line so this goes first
> * added `\rem` to the beginning of every other line.
> The end user would have to know that they shouldn't edit this 'Extra Book' as any added information will risk getting replaced should there be another input.

----------------

This probably involves editing books.ts to account for the extra book, but then have special handling since it's not writing "verses".

**Comment by sdysart** [comment]
The ID line should not begin with \rem.  That was probably a copy/paste
error on my part.
It should start with \id
